name: psm
description: PSM (Pubspec Management) is a command-line tool for managing pubspec configurations in Flutter and Dart projects. It allows developers to easily switch between different flavor configurations, such as development, testing, and production environments, by managing different pubspec files to achieve quick configuration switching.
version: 0.0.1
repository: https://github.com/goweii/psm
issue_tracker: https://github.com/goweii/psm/issues

environment:
  sdk: ^3.9.2

dependencies:
  args: ^2.7.0
  path: ^1.9.0
  yaml: ^3.1.3
  yaml_writer: ^2.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
