name: psm
description: A sample command-line application with basic argument parsing.
version: 0.0.1
repository: https://github.com/goweii/psm

environment:
  sdk: ^3.9.2

dependencies:
  args: ^2.7.0
  path: ^1.9.0
  yaml: ^3.1.3
  yaml_writer: ^2.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
