# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Compile PSM exe

on:
  push:
    branches: [ "main" ]
    paths:
      - "pubspec.yaml"

permissions:
  # 允许写入内容（如创建发布）
  contents: write

jobs:
  build_on_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      - name: Compile exe
        run: dart compile exe --target-os macos --output psm ./bin/psm.dart

      # 上传编译产物文件
      - name: Upload MacOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-release
          path: psm
          retention-days: 1

  build_on_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      - name: Compile exe
        run: dart compile exe --target-os windows --output psm ./bin/psm.dart

      # 上传编译产物文件
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: psm
          retention-days: 1

  build_on_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      - name: Compile exe
        run: dart compile exe --target-os linux --output psm ./bin/psm.dart

      # 上传编译产物文件
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-release
          path: psm
          retention-days: 1

  create_release:
    needs: [build_on_macos, build_on_windows, build_on_linux]
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      # 从 pubspec.yaml 中读取版本号
      - name: Get version from pubspec.yaml
        run: echo "VERSION=$(awk '/^version:/ {print $2}' pubspec.yaml)" >> $GITHUB_ENV

      # 创建 artifact 目录
      - name: Create artifact directory
        run: mkdir -p artifact

      # 下载缓存文件
      - name: Download MacOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-release
          path: artifact/macos
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-release
          path: artifact/windows
      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-release
          path: artifact/linux

      # 重命名并压缩文件，保持原始文件名
      - name: Prepare MacOS release asset
        run: |
          chmod +x artifact/macos/psm
          cd artifact/macos && zip -r ../macos-release.zip psm
      - name: Prepare Windows release asset
        run: |
          cd artifact/windows && zip -r ../windows-release.zip psm
      - name: Prepare Linux release asset
        run: |
          chmod +x artifact/linux/psm
          cd artifact/linux && zip -r ../linux-release.zip psm

      # 创建 Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: |
            Automatic release for version ${{ env.VERSION }}
          draft: false
          prerelease: false

      # 上传缓存文件到 Release
      - name: Upload MacOS Cache to Release
        id: upload_macos_cache
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifact/macos-release.zip
          asset_name: macos-release.zip
          asset_content_type: application/zip
      - name: Upload Windows Cache to Release
        id: upload_windows_cache
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifact/windows-release.zip
          asset_name: windows-release.zip
          asset_content_type: application/zip
      - name: Upload Linux Cache to Release
        id: upload_linux_cache
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifact/linux-release.zip
          asset_name: linux-release.zip
          asset_content_type: application/zip